proTeamArray = [("BOS","Boston Bruins","BOS.png"),
    ("BUF","Buffalo Sabres","BUF.png"),
    ("CGY","Calgary Flames","CGY.png"),
    ("CHI","Chicago Blackhawks","CHI.png"),
    ("DET","Detroit Red Wings","DET.png"),
    ("EDM","Edmonton Oilers","EDM.png"),
    ("CAR","Carolina Hurricanes","CAR.png"),
    ("LA","Los Angeles Kings","LA.png"),
    ("DAL","Dallas Stars","DAL.png"),
    ("MTL","Montréal Canadiens","MTL.png"),
    ("NJ","New Jersey Devils","NJ.png"),
    ("NYI","New York Islanders","NYI.png"),
    ("NYR","New York Rangers","NYR.png"),
    ("OTT","Ottawa Senators","OTT.png"),
    ("PHI","Philadelphia Flyers","PHI.png"),
    ("PIT","Pittsburgh Penguins","PIT.png"),
    ("COL","Colorado Avalanche","COL.png"),
    ("SJ","San Jose Sharks","SJ.png"),
    ("STL","St. Louis Blues","STL.png"),
    ("TB","Tampa Bay Lightning","TB.png"),
    ("TOR","Toronto Maple Leafs","TOR.png"),
    ("VAN","Vancouver Canucks","VAN.png"),
    ("WSH","Washington Capitals","WSH.png"),
    ("ARI","Arizona Coyotes","ARI.png"),
    ("ANA","Anaheim Ducks","ANA.png"),
    ("FLA","Florida Panthers","FLA.png"),
    ("NSH","Nashville Predators","NSH.png"),
    ("WPG","Winnipeg Jets","WPG.png"),
    ("CBJ","Columbus Blue Jackets","CBJ.png"),
    ("MIN","Minnesota Wild","MIN.png"),
    ("VGK","Vegas Golden Knights","VGK.png"),
    ("SEA","Seattle Kraken","SEA.png")
]